/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Main.java
 *
 * Created on 16/09/2009, 12:22:59 PM
 */
package simulacion.interfaz;

import java.awt.Dialog.ModalExclusionType;
import java.io.File;
import java.io.IOException;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import org.netbeans.api.visual.widget.Widget;
import org.openide.util.Exceptions;
import problema.mochila.EjercicioMochila;
import problema.viajero.EjercicioViajero;
import problema.viajero.EsquemaViajero;
import problema.viajero.Punto;
import problema.viajero.SolucionViajero;
import simulacion.Util;
import simulacion.interfaz.mochila.FiltroKNP;
import simulacion.interfaz.viajero.Arco;
import simulacion.interfaz.viajero.FiltroTSP;
import simulacion.interfaz.viajero.GrafoViajeroScene;
import simulacion.simulatedAnnealing.Ejercicio;

/**
 *
 * @author John Arevalo
 * @author Jenny Bernal
 *
 */
public class Main extends javax.swing.JFrame {

    /** Creates new form Main */
    private Ejercicio ejercicio;
    private GrafoViajeroScene grafoViajero;

    public Main() throws IOException {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        barraHerramientas = new javax.swing.JToolBar();
        botonAbrirArchivo = new javax.swing.JButton();
        botonEjecutar = new javax.swing.JButton();
        scrollPanelViajero = new javax.swing.JScrollPane();
        panelViajero = new javax.swing.JPanel();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuAbrirViajero = new javax.swing.JMenuItem();
        menuAbrirMochila = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        menuEdicion = new javax.swing.JMenu();
        menuEjecutar = new javax.swing.JMenuItem();
        menuPreferencias = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Algoritmos de Simulacion");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        barraHerramientas.setFloatable(false);
        barraHerramientas.setRollover(true);

        botonAbrirArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulacion/interfaz/imagenes/abrirarchivo.png"))); // NOI18N
        botonAbrirArchivo.setToolTipText("Abrir Archivo...");
        botonAbrirArchivo.setFocusable(false);
        botonAbrirArchivo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAbrirArchivo.setMargin(new java.awt.Insets(10, 10, 10, 10));
        botonAbrirArchivo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAbrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAbrirArchivoActionPerformed(evt);
            }
        });
        barraHerramientas.add(botonAbrirArchivo);

        botonEjecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simulacion/interfaz/imagenes/ejecutar.png"))); // NOI18N
        botonEjecutar.setToolTipText("Ejecutar");
        botonEjecutar.setFocusable(false);
        botonEjecutar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonEjecutar.setMargin(new java.awt.Insets(10, 10, 10, 10));
        botonEjecutar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEjecutarActionPerformed(evt);
            }
        });
        barraHerramientas.add(botonEjecutar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(barraHerramientas, gridBagConstraints);

        panelViajero.setLayout(new java.awt.BorderLayout());
        scrollPanelViajero.setViewportView(panelViajero);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(scrollPanelViajero, gridBagConstraints);

        menuArchivo.setText("Archivo");

        menuAbrirViajero.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        menuAbrirViajero.setText("Abrir Archivo...");
        menuAbrirViajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirViajeroActionPerformed(evt);
            }
        });
        menuArchivo.add(menuAbrirViajero);

        menuAbrirMochila.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        menuAbrirMochila.setText("Abrir Mochila...");
        menuAbrirMochila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirMochilaActionPerformed(evt);
            }
        });
        menuArchivo.add(menuAbrirMochila);

        menuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuSalir);

        barraMenu.add(menuArchivo);

        menuEdicion.setText("Edicion");

        menuEjecutar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        menuEjecutar.setText("ejecutar");
        menuEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEjecutarActionPerformed(evt);
            }
        });
        menuEdicion.add(menuEjecutar);

        menuPreferencias.setText("Preferencias...");
        menuPreferencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPreferenciasActionPerformed(evt);
            }
        });
        menuEdicion.add(menuPreferencias);

        barraMenu.add(menuEdicion);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAbrirViajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirViajeroActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        File archivo;

        fileChooser.addChoosableFileFilter(new FiltroKNP());
        fileChooser.addChoosableFileFilter(new FiltroTSP());
        fileChooser.addChoosableFileFilter(new FiltroGeneral());
        fileChooser.showOpenDialog(this);

        if ((archivo = fileChooser.getSelectedFile()) == null) {
            return;
        }
        try {
            if (Util.getExtension(archivo).equalsIgnoreCase("tsp")) {
                ejercicio = new EjercicioViajero(archivo);
                dibujarNodos();
            } else if (Util.getExtension(archivo).equalsIgnoreCase("knp")) {
                ejercicio = new EjercicioMochila(archivo);
            } else {
                throw new Exception("Formato de archivo no válido");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar el archivo:" + ex.getMessage(),
                    "Error en carga",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menuAbrirViajeroActionPerformed

    private void dibujarNodos() {

        EsquemaViajero viajero = ((EjercicioViajero) ejercicio).getViajero();
        Widget nodo;
        for (Punto punto : viajero.getPuntos()) {
            nodo = grafoViajero.addNode(punto);
            nodo.setPreferredLocation(viajero.trasladar(punto, panelViajero.getBounds()));
        }

        panelViajero.add(grafoViajero.createView(), java.awt.BorderLayout.CENTER);
    }

    private void dibujarSolucion() {
        SolucionViajero solucion = (SolucionViajero) ejercicio.getMejorSolucion();
        Punto anterior = solucion.getRuta().get(0);
        Arco arco;
        for (Punto punto : solucion.getRuta()) {
            arco = new Arco(anterior.getCostoA(punto));
            grafoViajero.addEdge(arco);
            grafoViajero.setEdgeSource(arco, anterior);
            grafoViajero.setEdgeTarget(arco, punto);
            anterior = punto;
        }
        arco = new Arco(anterior.getCostoA(solucion.getRuta().get(0)));
        grafoViajero.addEdge(arco);
        grafoViajero.setEdgeSource(arco, anterior);
        grafoViajero.setEdgeTarget(arco, solucion.getRuta().get(0));
    }

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuAbrirMochilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirMochilaActionPerformed
    }//GEN-LAST:event_menuAbrirMochilaActionPerformed

    private void menuEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEjecutarActionPerformed
        ejercicio.ejecutar();
        dibujarSolucion();
        System.out.println("Mejor Solucion" + ejercicio.getMejorSolucion());
    }//GEN-LAST:event_menuEjecutarActionPerformed

    private void botonAbrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbrirArchivoActionPerformed
        menuAbrirViajeroActionPerformed(evt);
    }//GEN-LAST:event_botonAbrirArchivoActionPerformed

    private void botonEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEjecutarActionPerformed
        menuEjecutarActionPerformed(evt);
    }//GEN-LAST:event_botonEjecutarActionPerformed

    private void menuPreferenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPreferenciasActionPerformed
        ConfiguracionUI panelConfiguracion;

        if (ejercicio != null) {
            panelConfiguracion = new ConfiguracionUI(ejercicio.getConfiguracion());
        } else {
            panelConfiguracion = new ConfiguracionUI();
        }
        JDialog dialog = new JDialog();
        dialog.setContentPane(panelConfiguracion);
        dialog.setTitle("Configuración");
        dialog.setModal(true);
        dialog.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
        dialog.pack();
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
        ejercicio.setConfiguracion(panelConfiguracion.getConfiguracion());
    }//GEN-LAST:event_menuPreferenciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            // Set cross-platform Java L&F (also called "Metal")
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (Exception exc) {
        }

        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    Main frame = new Main();
                    frame.setVisible(true);
                    frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
                } catch (IOException ex) {
                    Exceptions.printStackTrace(ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barraHerramientas;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton botonAbrirArchivo;
    private javax.swing.JButton botonEjecutar;
    private javax.swing.JMenuItem menuAbrirMochila;
    private javax.swing.JMenuItem menuAbrirViajero;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuEdicion;
    private javax.swing.JMenuItem menuEjecutar;
    private javax.swing.JMenuItem menuPreferencias;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JPanel panelViajero;
    private javax.swing.JScrollPane scrollPanelViajero;
    // End of variables declaration//GEN-END:variables
}
