/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MochilaUI.java
 *
 * Created on 18/11/2009, 11:41:35 AM
 */
package simulacion.interfaz.mochila;

import problema.mochila.EjercicioMochila;

/**
 *
 * @author John Arevalo
 */
public class MochilaUI extends javax.swing.JPanel {

    /** Creates new form MochilaUI */
    public MochilaUI(EjercicioMochila ejercicio) {
        initComponents();
        tableMochila.setModel(new MochilaTableModel(ejercicio));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollMochila = new javax.swing.JScrollPane();
        tableMochila = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        scrollMochila.setViewportView(tableMochila);

        add(scrollMochila, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollMochila;
    private javax.swing.JTable tableMochila;
    // End of variables declaration//GEN-END:variables
}
